name: Java CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        node-version: '20'   # Add node-version parameter with value '20'

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'   # Also, ensure to specify the distribution

    - name: Build with Maven
      run: mvn -B clean package

    - name: Run tests
      run: mvn test
